name: Semgrep Scan

on: push

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: semgrep-action
      uses: returntocorp/semgrep-action@v1
      env:
        WORKSPACE: ""
