name: Semgrep Scan

on: push

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
      - name: install semgrep and scan
        run: |
            echo "exploring"
            pwd
            ls - al /home/
            ls - al /home/runner/
            ls - al /home/runner/work/
            ls - al /home/runner/work/DVWA/
            ls - al /home/runner/work/DVWA/DVWA
            python3 -m pip install semgrep
            echo "path: " 
            pwd
            echo "ls:" 
            ls -al
            semgrep --config=auto .


