name: Semgrep Scan

on: push

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
      - name: install semgrep and scan
        run: |
            echo "exploring"
            python3 -m pip install semgrep
            semgrep --config=auto .
