name: Semgrep Scan

on: push

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            python3 -m pip install semgrep
            semgrep --config=auto


