name: Semgrep Scan

on: push

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
      - name: install semgrep and scan
        env:
          WORKSPACE: ""
        run: |
            pwd
            python3 -m pip install semgrep
            semgrep --config=auto


